### ISSUE TITLE
Fine-Grained-Image issue

### ISSUE THREAD

**Issue by haidog-yaqub** [yamiefun/Fine-Grained-Image-Classification#1]
It seems like just the resnet, how did you use it to do Fine-Grained-Image classification?

**Comment by yamiefun** [comment]
Resnet can work with fine-grained image classification problem because fine-grained image classification is a subfield of image classification. But apparently, the result accuracy may not meet your expectation. If you need a more accurate model, you should try some state-of-the-art methods.
![image](https://user-images.githubusercontent.com/34006713/100063003-7426a480-2e6b-11eb-9458-c3441239a717.png)

**Comment by haidog-yaqub** [comment]
> Resnet can work with fine-grained image classification problem because fine-grained image classification is a subfield of image classification. But apparently, the result accuracy may not meet your expectation. If you need a more accurate model, you should try some state-of-the-art methods.
> ![image](https://user-images.githubusercontent.com/34006713/100063003-7426a480-2e6b-11eb-9458-c3441239a717.png)

got it, thanks bro!
